behaviors:
  Rabbit:
    trainer_type: ppo
    hyperparameters:    
      batch_size: 800
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.006
      epsilon: 0.22
      lambd: 0.94
      num_epoch: 5
      learning_rate_schedule:   constant
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   3
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.94
        strength: 1.0
    keep_checkpoints:   5
    checkpoint_interval:    500000
    max_steps:  15000000
    time_horizon:   64
    summary_freq:   20000
    threaded:   true
  Fox:
    trainer_type: ppo
    hyperparameters:    
      batch_size: 800
      buffer_size: 100000
      learning_rate: 0.0001
      beta: 0.006
      epsilon: 0.22
      lambd: 0.94
      num_epoch: 5
      learning_rate_schedule:   constant
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   3
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.94
        strength: 1.0
    keep_checkpoints:   5
    checkpoint_interval:    500000
    max_steps:  15000000
    time_horizon:   64
    summary_freq:   20000
    threaded:   true