behaviors:
  Rabbit:
    trainer_type: ppo
    hyperparameters:
      batch_size: 800
      buffer_size: 16000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule:   linear
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   3
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints:   10
    checkpoint_interval:    1000000
    max_steps:  40000000
    time_horizon:   256
    summary_freq:   20000
    threaded:   true
  Fox:
    trainer_type: ppo
    hyperparameters:
      batch_size: 800
      buffer_size: 16000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule:   linear
    network_settings:   
      normalize:    false
      hidden_units: 128
      num_layers:   3
      vis_encode_type:  simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints:   10
    checkpoint_interval:    1000000
    max_steps:  40000000
    time_horizon:   256
    summary_freq:   20000
    threaded:   true